# Generated by Django 3.2.16 on 2022-11-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field=270, help_text='Изображение товара', upload_to='images/', verbose_name='Изображение товара', width_field=270),
        ),
    ]
