# Generated by Django 3.2.16 on 2022-11-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение товара', upload_to='items/', verbose_name='Изображение товара'),
        ),
    ]
