# Generated by Django 3.2.16 on 2022-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование валюты')),
                ('alphabetic_code', models.CharField(max_length=5, verbose_name='Код валюты')),
                ('currency_symbol', models.CharField(max_length=3, verbose_name='Символ валюты')),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс обмена')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ('name',),
            },
        ),
    ]
